### PR TITLE
Create commands when they do not already exist

### PR DESCRIPTION
**Pull request by smith61**
Make CommandHandler create and register commands when they do not already exist.
Also allowed library to be loaded as a bukkit plugin.

### CODE REVIEW

**Comment by coaster3000** [comment]
Is there a non Hacky way to do this?

I still like this though.

**Comment by smith61** [comment]
Not really. Bukkit doesn't leak the CommandMap. It may be possible to write a parsing tool to add the commands to the plugin.yml. I don't think this is possible during runtime without unpacking and repacking the plugin jar.

**Comment by coaster3000** [comment]
Yea... How often do you think it could break on bukkit updates...

**Comment by smith61** [comment]
Those fields have not changed in quite a while so I don't believe it will break often. If need be there are two places where the CommandMap is stored(CraftServer, PluginManager). You could loop through all fields in both classes until a field is found of the type CommandMap. I don't think that is necessary as the field is contained in SimplePluginManager which is part of the Bukkit api and has not changed recently. If it breaks it is a simple update

**Comment by Ranzdo** [comment]
Sorry, but I think I have to decline this pull request. I have already toyed with the idea to insert commands directly into CommandMap, however I diden't implement because of:
- Compatibility issue. Using reflection on an API to get around it functions is never a good idea and is not supported by Bukkit (otherwise they would have implemented API calls).
- Fallback issue. What happens if a plugin already uses the command identifier? If you use the plugin.yml you don't need to worry about that since bukkit will choose one of your alias if a plugin already uses the plugin and will warn the user if two plugins are fighting over one command identifier. However in this pull request the command would never be added if a plugin was conflicting with it and just throw an exception that describes the error incorrect, which can lead to confusion.
- It is lazy unsupported programming. It is not worth the 2 sec you will have to put at least the root command into the plugin.yml risking the issues above. The bukkit team have the user put the command into the plugin.yml for a reason and that is what they support.

However, thank you for your consideration and I hope you will understand my reasons for it.

**Pull request closed without merging**
